/*
 * getValidAccountInfoGsims
 * getValidAccountInfoGsims
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BusinessQueryErrorResponse;
import io.swagger.client.model.QueryErrorResponse;
import io.swagger.client.model.SystemQueryErrorResponse;
import io.swagger.client.model.ValidAccountInfoGsimsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * getValidAccountInfoGsims
     *
     * getValidAccountInfoGsims
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getValidAccountInfoGsimsTest() throws ApiException {
        String accountId = null;
        String credentials = null;
        String companyId = null;
        String deviceId = null;
        String userRole = null;
        String disablePagination = null;
        String idType = null;
        String documentId = null;
        Integer pageSize = null;
        Integer pageStart = null;
        String pageToken = null;
        ValidAccountInfoGsimsResponse response = api.getValidAccountInfoGsims(accountId, credentials, companyId, deviceId, userRole, disablePagination, idType, documentId, pageSize, pageStart, pageToken);

        // TODO: test validations
    }
    
}
