/*
 * getValidAccountInfoGsims
 * getValidAccountInfoGsims
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ErrorHeader;
import io.swagger.client.model.SystemQueryErrorResponseBody;
import java.io.IOException;

/**
 * SystemQueryErrorResponse
 */
@ApiModel(description = "SystemQueryErrorResponse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-26T14:59:51.353+06:00")
public class SystemQueryErrorResponse {
  @SerializedName("header")
  private ErrorHeader header = null;

  @SerializedName("error")
  private SystemQueryErrorResponseBody error = null;

  public SystemQueryErrorResponse header(ErrorHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public ErrorHeader getHeader() {
    return header;
  }

  public void setHeader(ErrorHeader header) {
    this.header = header;
  }

  public SystemQueryErrorResponse error(SystemQueryErrorResponseBody error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public SystemQueryErrorResponseBody getError() {
    return error;
  }

  public void setError(SystemQueryErrorResponseBody error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemQueryErrorResponse systemQueryErrorResponse = (SystemQueryErrorResponse) o;
    return Objects.equals(this.header, systemQueryErrorResponse.header) &&
        Objects.equals(this.error, systemQueryErrorResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemQueryErrorResponse {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

