/*
 * getValidAccountInfoGsims
 * getValidAccountInfoGsims
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.QueryHeader;
import io.swagger.client.model.ValidAccountInfoGsimsResponseBody;
import java.io.IOException;

/**
 * ValidAccountInfoGsimsResponse
 */
@ApiModel(description = "ValidAccountInfoGsimsResponse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-26T14:59:51.353+06:00")
public class ValidAccountInfoGsimsResponse {
  @SerializedName("header")
  private QueryHeader header = null;

  @SerializedName("body")
  private ValidAccountInfoGsimsResponseBody body = null;

  public ValidAccountInfoGsimsResponse header(QueryHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public QueryHeader getHeader() {
    return header;
  }

  public void setHeader(QueryHeader header) {
    this.header = header;
  }

  public ValidAccountInfoGsimsResponse body(ValidAccountInfoGsimsResponseBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public ValidAccountInfoGsimsResponseBody getBody() {
    return body;
  }

  public void setBody(ValidAccountInfoGsimsResponseBody body) {
    this.body = body;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidAccountInfoGsimsResponse validAccountInfoGsimsResponse = (ValidAccountInfoGsimsResponse) o;
    return Objects.equals(this.header, validAccountInfoGsimsResponse.header) &&
        Objects.equals(this.body, validAccountInfoGsimsResponse.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, body);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidAccountInfoGsimsResponse {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

