/*
 * getValidAccountInfoGsims
 * getValidAccountInfoGsims
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ValidAccountInfoGsimsResponseBodyInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-26T14:59:51.353+06:00")
public class ValidAccountInfoGsimsResponseBodyInner {
  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("mobilePhoneNumber")
  private String mobilePhoneNumber = null;

  @SerializedName("response")
  private String response = null;

  @SerializedName("accountTitle")
  private String accountTitle = null;

  @SerializedName("mobileNumber")
  private String mobileNumber = null;

  @SerializedName("accountType")
  private String accountType = null;

  @SerializedName("email")
  private String email = null;

  public ValidAccountInfoGsimsResponseBodyInner accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Identifier of the account. Often referred to as the account number, yet for consistency this is always referred to as accountId. Accepts both IBAN &amp; BBAN
   * @return accountId
  **/
  @ApiModelProperty(value = "Identifier of the account. Often referred to as the account number, yet for consistency this is always referred to as accountId. Accepts both IBAN & BBAN")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public ValidAccountInfoGsimsResponseBodyInner mobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
    return this;
  }

   /**
   * Represents the phone number of a customer
   * @return mobilePhoneNumber
  **/
  @ApiModelProperty(value = "Represents the phone number of a customer")
  public String getMobilePhoneNumber() {
    return mobilePhoneNumber;
  }

  public void setMobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
  }

  public ValidAccountInfoGsimsResponseBodyInner response(String response) {
    this.response = response;
    return this;
  }

   /**
   * The OFS response sent from T24 for the request sent for funds reservation or deletion of the reservation
   * @return response
  **/
  @ApiModelProperty(value = "The OFS response sent from T24 for the request sent for funds reservation or deletion of the reservation")
  public String getResponse() {
    return response;
  }

  public void setResponse(String response) {
    this.response = response;
  }

  public ValidAccountInfoGsimsResponseBodyInner accountTitle(String accountTitle) {
    this.accountTitle = accountTitle;
    return this;
  }

   /**
   * Short title on an account
   * @return accountTitle
  **/
  @ApiModelProperty(value = "Short title on an account")
  public String getAccountTitle() {
    return accountTitle;
  }

  public void setAccountTitle(String accountTitle) {
    this.accountTitle = accountTitle;
  }

  public ValidAccountInfoGsimsResponseBodyInner mobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Mobile number of the customer
   * @return mobileNumber
  **/
  @ApiModelProperty(value = "Mobile number of the customer")
  public String getMobileNumber() {
    return mobileNumber;
  }

  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }

  public ValidAccountInfoGsimsResponseBodyInner accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Groups the products based on their type, eg, Checking, Savings, CD etc,.
   * @return accountType
  **/
  @ApiModelProperty(value = "Groups the products based on their type, eg, Checking, Savings, CD etc,.")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public ValidAccountInfoGsimsResponseBodyInner email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email Identifier of the Customer
   * @return email
  **/
  @ApiModelProperty(value = "Email Identifier of the Customer")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidAccountInfoGsimsResponseBodyInner validAccountInfoGsimsResponseBodyInner = (ValidAccountInfoGsimsResponseBodyInner) o;
    return Objects.equals(this.accountId, validAccountInfoGsimsResponseBodyInner.accountId) &&
        Objects.equals(this.mobilePhoneNumber, validAccountInfoGsimsResponseBodyInner.mobilePhoneNumber) &&
        Objects.equals(this.response, validAccountInfoGsimsResponseBodyInner.response) &&
        Objects.equals(this.accountTitle, validAccountInfoGsimsResponseBodyInner.accountTitle) &&
        Objects.equals(this.mobileNumber, validAccountInfoGsimsResponseBodyInner.mobileNumber) &&
        Objects.equals(this.accountType, validAccountInfoGsimsResponseBodyInner.accountType) &&
        Objects.equals(this.email, validAccountInfoGsimsResponseBodyInner.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, mobilePhoneNumber, response, accountTitle, mobileNumber, accountType, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidAccountInfoGsimsResponseBodyInner {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    mobilePhoneNumber: ").append(toIndentedString(mobilePhoneNumber)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    accountTitle: ").append(toIndentedString(accountTitle)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

