/*
 * AcBal
 * AcBalance
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AcBalResponseBody;
import io.swagger.client.model.QueryHeader;
import java.io.IOException;

/**
 * AcBalResponse
 */
@ApiModel(description = "AcBalResponse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-14T09:38:17.140Z")
public class AcBalResponse {
  @SerializedName("body")
  private AcBalResponseBody body = null;

  @SerializedName("header")
  private QueryHeader header = null;

  public AcBalResponse body(AcBalResponseBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public AcBalResponseBody getBody() {
    return body;
  }

  public void setBody(AcBalResponseBody body) {
    this.body = body;
  }

  public AcBalResponse header(QueryHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public QueryHeader getHeader() {
    return header;
  }

  public void setHeader(QueryHeader header) {
    this.header = header;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcBalResponse acBalResponse = (AcBalResponse) o;
    return Objects.equals(this.body, acBalResponse.body) &&
        Objects.equals(this.header, acBalResponse.header);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, header);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcBalResponse {\n");
    
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

