/*
 * AcBal
 * AcBalance
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BusinessQueryErrorResponseBody;
import io.swagger.client.model.ErrorHeader;
import java.io.IOException;

/**
 * BusinessQueryErrorResponse
 */
@ApiModel(description = "BusinessQueryErrorResponse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-14T09:38:17.140Z")
public class BusinessQueryErrorResponse {
  @SerializedName("error")
  private BusinessQueryErrorResponseBody error = null;

  @SerializedName("header")
  private ErrorHeader header = null;

  public BusinessQueryErrorResponse error(BusinessQueryErrorResponseBody error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public BusinessQueryErrorResponseBody getError() {
    return error;
  }

  public void setError(BusinessQueryErrorResponseBody error) {
    this.error = error;
  }

  public BusinessQueryErrorResponse header(ErrorHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public ErrorHeader getHeader() {
    return header;
  }

  public void setHeader(ErrorHeader header) {
    this.header = header;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessQueryErrorResponse businessQueryErrorResponse = (BusinessQueryErrorResponse) o;
    return Objects.equals(this.error, businessQueryErrorResponse.error) &&
        Objects.equals(this.header, businessQueryErrorResponse.header);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, header);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessQueryErrorResponse {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

